### ISSUE TITLE
Feature: remove progress number row if not present. 

### ISSUE THREAD

**Issue by Franchute13** [emreesen27/Flutter-Progress-Dialog#11]
Hello.
Is it possible to delete the row of the number that indicates the progress if this data is not indicated (_progress)? 
We only use the circular progress and the text. 
The problem is that when the progress number is empty it leaves a blank row and this leaves the circular progress and the text off center with respect to the dialog box. 
I add an image to show the problem. 
Please also see if horizontal centering can be added as an option.
![Progress-Dialog-center](https://user-images.githubusercontent.com/5639694/160147222-7de264e9-6691-4bed-bbf6-31867ecd576d.jpg)

**Comment by emreesen27** [comment]
Hi @Franchute13 

I didn't think the library would be used in this way.

* upgrade version
```yaml
1.0.6
```
* now you can use
```dart
hideValue = true
msgTextAlign: TextAlign.center (Default)
```

**Comment by Franchute13** [comment]
Hello.
 Thanks for your quick response.
 It works perfectly.
Thanks.
