### ISSUE TITLE
Bug: Custom message font weight ignored

### ISSUE THREAD

**Issue by jongkb** [emreesen27/Flutter-Progress-Dialog#14]
`ProgressDialog.show()` method accepts custom message font weight using `msqFontWeight` (typo?) named parameter but it does nothing.

**Actual result**

Message always appear in bold.

**Expected result**

Message should use the user-specified font weight.

Plugin version: 1.0.7

**Comment by emreesen27** [comment]
yes you are right, please upgrade to **1.0.8**

You can now use it.
