### ISSUE TITLE
build failed with  asset: packages/sn_progress_dialog/completed.png. missing

### ISSUE THREAD

**Issue by BrianTum** [emreesen27/Flutter-Progress-Dialog#18]
> Task :app:compileFlutterBuildDebug
Error detected in pubspec.yaml:
No file or variants found for asset: packages/sn_progress_dialog/completed.png.

**Comment by emreesen27** [comment]
Hi @BrianTum 
Are you using it like this ?
```dart
completed: Completed()
```
If you are trying to add an icon yourself, please check the spaces and the icon path.
