### ISSUE TITLE
Dialog does not close anymore after `1.0.9` update

### ISSUE THREAD

**Issue by enricobenedos** [emreesen27/Flutter-Progress-Dialog#22]
Hello,

after the `1.0.9` update the dialog does not close anymore. We simply update from `1.0.8` to `1.0.9` and it stops working simply remaining opened even if we call `.close()` method.

Is it probably related to new delay changes in `1.0.9`? Because if this behaviour is expected this is a breaking change.

Thanks

**Comment by emreesen27** [comment]
Hello,

how do you use the function? I tried the cancel function in the examples in version 1.0.9 and it looks fine.

**Comment by enricobenedos** [comment]
This is an example function:
```dart
Future<void> showPDF() async {
    _pr.show(
        msg: 'Downloading PDF..',
        backgroundColor: Theme.of(context).scaffoldBackgroundColor,
        msgColor:
            Theme.of(context).textTheme.bodyText1?.color ?? Colors.black87,
        valueColor:
            Theme.of(context).textTheme.bodyText1?.color ?? Colors.black87,
        elevation: 10.0,
        max: 100,
        progressType: ProgressType.valuable,
        barrierColor: Colors.black54);

    final String currentLangCode =
        AppLocalizations.of(context).locale.languageCode;

    final PdfManager pdfManager = PdfManager(
        tourId: tour.id, tourCode: tour.code, langCode: currentLangCode);
    final String pdfTmpPath = await pdfManager.getGpxTemporaryPath();

    var dio = Dio();
    try {
      await dio.download(pdfManager.getPDFDownloadUrl(), pdfTmpPath,
          onReceiveProgress: (rec, total) {
        int progress = (((rec / total) * 100).toInt());
        _pr.update(value: progress);
      }, options: Options(headers: HttpInterceptor().getCustomHeaders()));

      _pr.close();
      await Navigator.of(context).push(MaterialPageRoute(
        builder: (context) {
          return TourPdfPage(
            pdfPath: pdfTmpPath,
            tourId: tour.id,
            tourCode: tour.code,
            langCode: currentLangCode,
          );
        },
        settings: const RouteSettings(name: 'TourPdfPage'),
      ));
    } catch (e) {
      _pr.close();
      debugPrint(
          "Exception generated during PDF retrieve, probably it not exist for tour id ${tour.id}");

      await GlobalMethods.showCustomDialog(
          context,
          AppLocalizations.of(context).translate('pdf_not_found_title'),
          AppLocalizations.of(context).translate('pdf_not_found_subtitle'));
    }
  }
```

this function is called by a `FloatingActionButton` in a normal page

**Comment by emreesen27** [comment]
I couldn't see any reason why dialog should not close, but if you are getting a non-caught exception, you may need to close the progress in the finally block.

```dart
  try {
       // download pdf
    } catch (e) {
      // debugPrint(e)
    }finally {
      // _pr.close();
    }
```
I also implemented an example similar to yours on android and didn't have any problems.

```dart
    ProgressDialog pd = ProgressDialog(context: context);
    pd.show(
        max: 100,
        msg: 'File Downloading...',
        progressBgColor: Colors.transparent);

    var downloadsPath = await AndroidPathProvider.downloadsPath;
    var dio = Dio();

    var status = await Permission.storage.status;
    if (!status.isGranted) {
      await Permission.storage.request();
    }

    try {
      await dio.download(
          "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
          downloadsPath + "dummy", onReceiveProgress: (rec, total) {
        int progress = (((rec / total) * 100).toInt());
        pd.update(value: progress);
      });
    } catch (e) {
      debugPrint(e.toString());
    } finally {
      pd.close();
    }
```
Thank you for your feedback.

**Comment by enricobenedos** [comment]
You are right, put `close()` inside `finally` block in this case is a best practice.

But there is something different between two versions, I'll check it as soon as possible. Probably can be my implementation mistake that shows a different library behavior.

**Comment by acamue** [comment]
hi
did you find any fix to this? close() is not working for me too...

**Comment by emreesen27** [comment]
hi @acamue 
Can you test if the close method works properly in the library's examples ?

**Comment by emreesen27** [comment]
@enricobenedos  I finally found what the problem was :)

The dialog cannot be closed because you added to Navigator before the progress dialog closed.

* You can manually close the dialog until you find a solution for delayed closed.

```dart 
   if(pd.isOpen()) {
      // Close it with a method according to your need
      // Navigator.pop(context); 
      // Navigator.of(context, rootNavigator: true).pop();
      // Navigator.of(context).pop();
    }
```
@acamue Probably something like this in your problem please check.

**Comment by enricobenedos** [comment]
What do you mean with:
> The dialog cannot be closed because you added to Navigator before the progress dialog closed.

I call `pr.close()` before navigator call, so what's wrong? Close is not awaitable so I expect all goes well.

**Comment by emreesen27** [comment]
Even if you do not delay, the closing function remains in the future object. This may be causing your navigator process to get in front of the dialog window.

* If you do not want to close it off manually, you can use it this way.
```dart
pd.show(
  onStatusChanged: (status) {
    if(status == DialogStatus.closed) {
      // navigate  to TourPdfPage
    }
  }
);
```

**Comment by emreesen27** [comment]
Upgrade to version 1.1.3. This issue has been resolved.
