### ISSUE TITLE
Message NOT Updated!

### ISSUE THREAD

**Issue by Aggie85** [emreesen27/Flutter-Progress-Dialog#28]
Howdy,

Calling update() with a changed msg value does NOT update unless I also change the value of the progress value.

I believe the problem is you are using a ValueListenableBuilder on _progress.

All the best,

Aggie85

**Comment by emreesen27** [comment]
Hi @Aggie85 

Actually my purpose for creating the library was to create a dialog that listens for the value. I guess it's mostly used to update the message value :)

I'm thinking of making a development that separates these two uses at the constructor stage, then I hope that this and similar problems will be resolved.

Thanks for your feedback

**Comment by Aggie85** [comment]
Howdy,

Thanks for quick answer.

Wouldn’t it be simpler to just create an object or map of values and listen to changes to the map?

All the best,

Aggie85

**Comment by emreesen27** [comment]
Actually I was planning to get rid of progress type and value dependency by using constructor. Please let me know if you have ideas to simplify the structure.

**Comment by emreesen27** [comment]
@Aggie85  Upgrade to version 1.1.3. You can now update the message value.
