### ISSUE TITLE
it looks so cool

### ISSUE THREAD

**Issue by nattawutxp** [emreesen27/Flutter-Progress-Dialog#31]
I think it looks cool.

**Comment by sslavchev** [comment]
I have a problem. When process ids done, and Progress Dialog need to close, it closes background widget, and showing black screen.
Please see attached image below.
![problem1](https://github.com/emreesen27/Flutter-Progress-Dialog/assets/6688795/66337de7-518d-470b-8d7a-7a5da89674cb)
