### ISSUE TITLE
On Close, close background widgets and showing black screen

### ISSUE THREAD

**Issue by sslavchev** [emreesen27/Flutter-Progress-Dialog#32]
have a problem. When process ids done, and Progress Dialog need to close, it closes background widget, and showing black screen.
Please see attached image below.
![problem1](https://github.com/emreesen27/Flutter-Progress-Dialog/assets/6688795/8d946110-ca72-456f-b24f-58d30b332205)

**Comment by emreesen27** [comment]
Can you share the code so that I can understand how you use it?

**Comment by sslavchev** [comment]
Hello.
Sorry for my late response.
Here is a haw I call the Progress Bar.
In first it is the Windows application. This application is connected to hardware devices and reading data from them.
This part is OK. I have a ProgressDialog in this part also, but have no problems with it.
In case when I save data I'm calling another instance of ProgressDialog. Them progress bar is shown and everything is OK. 
When calling 'completed' procedure and need to close progress bar automatically, it closes background application and stay on black screen.
Here it is and part of program code.

//function initializing ProgressDialog
showSaveDialog(BuildContext context) {
  sd = ProgressDialog(context: context);
  sd?.update(value: 0, msg: "Saving data. Please wait...");
  sd?.show(
      progressBgColor: Colors.transparent,
      max: 100,
      msg: 'Saving data...',
      cancel: Cancel(), // To use with default values
      completed: Completed(completedMsg: "Done!", completionDelay: 2500));
}

The function is calling from ElevatedButton in form

  @override
  Widget build(BuildContext context) {
    //Translate DropDwon Menus
    typeValItems = {
      i18manager.getString('frm_pager_menu_line20'): 0,
      i18manager.getString('frm_pager_menu_line21'): 1,
      i18manager.getString('frm_pager_menu_line22'): 2,
      i18manager.getString('frm_pager_menu_line23'): 3,
      i18manager.getString('frm_pager_menu_line24'): 4,
      i18manager.getString('frm_pager_menu_line25'): 5,
      i18manager.getString('frm_pager_menu_line26'): 6,
      i18manager.getString('frm_pager_menu_line27'): 7,
      i18manager.getString('frm_pager_menu_line28'): 8,
      i18manager.getString('frm_pager_menu_line34'): 14,
      i18manager.getString('frm_pager_menu_line35'): 15
    };

    zoneValItems = {
      i18manager.getString('frm_receiver_zone_1'): 0,
      i18manager.getString('frm_receiver_zone_2'): 1,
      i18manager.getString('frm_receiver_zone_3'): 2
    };

    relayValItems = {
      i18manager.getString('frm_relay_acc_1'): 0,
      i18manager.getString('frm_relay_acc_2'): 1,
      i18manager.getString('frm_relay_acc_3'): 2
    };

    alarmTypeValItems = {
      i18manager.getString('frm_alarm_type_0'): 0,
      i18manager.getString('frm_alarm_type_1'): 1
    };

    notificationValItems = {
      i18manager.getString('frm_notification_acc_0'): 0,
      i18manager.getString('frm_notification_acc_1'): 1
    };

    // loop in the map and getting all the keys
    menuTypeItems.clear();
    for (String key in typeValItems.keys) {
      menuTypeItems.add(DropdownMenuItem<String>(
        // items[key] this instruction get the value of the respective key
        value: key,
        // items[key] this instruction get the value of the respective key
        child: Text(key), // the respective key as value
      ));
    }

    menuZoneItems.clear();
    for (String key in zoneValItems.keys) {
      menuZoneItems.add(DropdownMenuItem<String>(
        // items[key] this instruction get the value of the respective key
        value: key,
        // items[key] this instruction get the value of the respective key
        child: Text(key), // the respective key as value
      ));
    }

    menuRelayItems.clear();
    for (String key in relayValItems.keys) {
      menuRelayItems.add(DropdownMenuItem<String>(
        // items[key] this instruction get the value of the respective key
        value: key,
        // items[key] this instruction get the value of the respective key
        child: Text(key), // the respective key as value
      ));
    }

    menuAlarmTypeItems.clear();
    for (String key in alarmTypeValItems.keys) {
      menuAlarmTypeItems.add(DropdownMenuItem<String>(
        // items[key] this instruction get the value of the respective key
        value: key,
        // items[key] this instruction get the value of the respective key
        child: Text(key), // the respective key as value
      ));
    }

    menuNotificationItems.clear();
    for (String key in notificationValItems.keys) {
      menuNotificationItems.add(DropdownMenuItem<String>(
        // items[key] this instruction get the value of the respective key
        value: key,
        // items[key] this instruction get the value of the respective key
        child: Text(key), // the respective key as value
      ));
    }

    getTransmittersLength(context);
    if (transmittersStart == 0) {
      transmittersEnd = transmittersStart + transmittersLength;
    }
    return NotificationListener(
        onNotification: (SizeChangedLayoutNotification notification) {
          Future.delayed(const Duration(milliseconds: 300), () {
            getTransmittersLength(context);
            transmittersStart = 0;
            transmittersEnd = transmittersStart + transmittersLength;
            dataToScreen(context); // transmitterBoxes(callback, context);
            callback(() {});
            print('resized!');
          });
          return true;
        },
        child: SizeChangedLayoutNotifier(
            child: Column(children: [
          getHeader(),
          Expanded(
              child: Container(
                  color: Colors.white,
                  width: double.infinity,
                  child: dataToScreen(
                      context) /*transmitterBoxes(callback, context)*/)),
          SizedBox(
              width: double.infinity,
              child: ColoredBox(
                color: Colors.white,
                child: Padding(
                    padding: const EdgeInsets.all(5),
                    child: Row(children: [
                      ElevatedButton(
                          child: Text(i18manager.getString('btnSave')),
                          onPressed: () {
                            showSaveDialog(context);
                            print('Save Transmitters');
                            readPogrammingFormScreen();
                            //_showMyDialog(context);
                          }),
                      const SizedBox(width: 7),
                      ElevatedButton(
                          child: Text(i18manager.getString('frm_clearall')),
                          onPressed: () {
                            for (var i = transmittersStart;
                                i < transmittersEnd;
                                i++) {
                              _tabRecords[i].nameController.text = '';
                              _tabRecords[i].idController.text = '';
                              _tabRecords[i].typeValController.text =
                                  'Opti scan';
                              _tabRecords[i].zoneValController.text =
                                  'Standart';
                              _tabRecords[i].relayValController.text = 'Relay1';
                              _tabRecords[i].alarmValController.text =
                                  'Alarm Notification';
                              _tabRecords[i].notificationValController.text =
                                  'Alarm time';
                            }
                            //print('test');
                          }),
                      const SizedBox(width: 10),
                      ElevatedButton(
                          child: const Icon(Icons.west, color: Colors.white),
                          onPressed: () {
                            getTransmittersLength(context);
                            if (transmittersStart > 0 &&
                                transmittersStart < transmittersLength) {
                              transmittersEnd = transmittersStart;
                              transmittersStart = 0;
                            } else {
                              transmittersStart -= transmittersLength;
                              if (transmittersStart < 0) {
                                transmittersStart =
                                    numberOfTransmitters - transmittersLength;
                              }
                              transmittersEnd =
                                  transmittersStart + transmittersLength;
                            }
                            dataToScreen(context);
                            /*transmitterBoxes(callback, context);*/
                            callback(() {});
                          }),
                      const SizedBox(width: 5),
                      ElevatedButton(
                          child: const Icon(Icons.east, color: Colors.white),
                          onPressed: () {
                            getTransmittersLength(context);
                            if (transmittersEnd >= numberOfTransmitters) {
                              transmittersEnd = 0;
                              transmittersStart = -transmittersLength;
                            }
                            transmittersStart += transmittersLength;
                            transmittersEnd =
                                transmittersStart + transmittersLength;
                            if (transmittersEnd > numberOfTransmitters) {
                              transmittersEnd = numberOfTransmitters;
                            }
                            dataToScreen(context);
                            /*transmitterBoxes(callback, context);*/
                            callback(() {});
                          })
                    ])),
              )),
          Container(
            width: double.infinity,
            height: 30.00,
            decoration: const BoxDecoration(
              image: DecorationImage(
                image: ExactAssetImage('images/footer.png'),
                fit: BoxFit.fill,
              ),
            ),
          )
        ])));
  }
  
  I cannot find any solution to fix this. I'm trying some things but I'm going to the same result.
  Thank you for your fast response.
  Have a nice day.
  Svetoslav

**Comment by emreesen27** [comment]
I don't understand how you got the "done" message. Because according to your code you are not updating progress to max value anywhere

**Comment by sslavchev** [comment]
Yes, It is short version of code where value is set to 100% when push button. After completionDelay the ProgressDialog close the application window not it self.

**Comment by emreesen27** [comment]
I think you are operating on the navigator before the dialog closes. That way the dialog stays open and you lose the back screen.

**Comment by sslavchev** [comment]
Hello sorry. I found the problem. Problem was in context. I'm creating dynamic context and set it to the ProgressDialog. When reading your sources and found, to problem will causes only if context is wrong. 
Thank you for your support.
Have a nice day.

**Comment by sslavchev** [comment]
This is not a bug. Sorry.
