### ISSUE TITLE
can not pop

### ISSUE THREAD

**Issue by MrLiuYunPing** [emreesen27/Flutter-Progress-Dialog#33]
void _closeDialog() {
    if (_dialogIsOpen) {
      Navigator.of(context, rootNavigator: true).pop();
      _dialogIsOpen = false;
      _setDialogStatus(DialogStatus.closed);
    }
  }
Future<T?> showDialog<T>({
  required BuildContext context,
  required WidgetBuilder builder,
  bool barrierDismissible = true,
  Color? barrierColor = Colors.black54,
  String? barrierLabel,
  bool useSafeArea = true,
  bool useRootNavigator = true,
  RouteSettings? routeSettings,
  Offset? anchorPoint,
}) {...}
_closeDialog() should add ->rootNavigator: true

**Comment by emreesen27** [comment]
Hi @MrLiuYunPing 
Sorry for the late response, please check out this [PR](https://github.com/emreesen27/Flutter-Progress-Dialog/pull/34)
You can upgrade it to version 1.1.4.

**Comment by emreesen27** [comment]
Since there is no response, I am closing the issue.
