### ISSUE TITLE
Regarding null safety

### ISSUE THREAD

**Issue by yash-garg** [emreesen27/Flutter-Progress-Dialog#4]
Is Null Safety Version of this Package coming any time soon?

**Comment by emreesen27** [comment]
I will deal with this issue as soon as possible.

**Comment by yash-garg** [comment]
Thanks for the quick update!

**Comment by emreesen27** [comment]
@Yash-Garg You can switch to version 1.0.0-nullsafety.0.
https://pub.dev/packages/sn_progress_dialog/versions/1.0.0-nullsafety.0

**Comment by yash-garg** [comment]
> @Yash-Garg You can switch to version 1.0.0-nullsafety.0.
> https://pub.dev/packages/sn_progress_dialog/versions/1.0.0-nullsafety.0

Great! Thank you
