### ISSUE TITLE
Feature Request: Allow Dynamic Updates to completed Message in ProgressDialog

### ISSUE THREAD

**Issue by alexaungmyooo** [emreesen27/Flutter-Progress-Dialog#40]
First of all, thank you for creating and maintaining this awesome package! It has been incredibly useful for my project, and I appreciate all the work you've put into it.

**Feature Request:**
Currently, the ProgressDialog class allows updating progress through the value and msg parameters in the pd.update() method. However, the completed message is static and must be defined when ProgressDialog is initially shown. This limitation makes it challenging to dynamically reflect the final state of the process in the completed message.

It would be extremely helpful if the pd.update() method could also accept a completed parameter so that the final message can be updated dynamically based on the current state.

**Proposed Solution:**
Allow pd.update() to accept a completed parameter. For example:

```
pd.update(
  value: progress,
  msg: "${migratedFiles} / ${totalFiles} files migrated",
  completed: Completed(
    completedMsg: """
Migration Complete.
Total Files: $totalFiles
Migrated: $migratedFiles
Skipped: $skippedFiles
    """,
    completionDelay: 5000,
  ),
);
```
**Benefits:**
Dynamic updates to the completed message ensure the final summary reflects the actual state.
It eliminates the need for workarounds like manually displaying a separate dialog or UI component for the completion summary.

**Additional Context:**
Here’s a use case where this feature would be beneficial:

I am implementing a file migration feature where files are processed in a loop. As each file is processed, I update the progress bar using pd.update(). However, the completed message currently only shows the initial state because it cannot be updated dynamically. Adding this feature would improve the user experience by showing an accurate summary at the end of the migration.
Please let me know if you'd like more details or if I can contribute to this enhancement.

Thank you for considering this request!

**Comment by emreesen27** [comment]
Hello, thank you for your kind words.

I would like to make an adjustment as you suggested, but I'm not entirely sure about the solution part. Instead of reassigning the Completed class, would adding a new message variable inside the class be a better approach ?

* Let's add this variable to the Completed class.
`  final Future<String>? completedMsgFuture;`

* We decide which message value to use within the show function.

```
 if (completed?.completedMsgFuture != null) {
      completed!.completedMsgFuture!.then((newMsg) {
        _completedMsg.value = newMsg;
      });
    } else if (completed != null) {
      _completedMsg.value = completed.completedMsg;
    }
```

**Here's how you can implement this solution**

* Let's assume you are waiting for an asynchronous value.

```
  Future<String> getDelayedMessage() async {
    await Future.delayed(Duration(seconds: 1));
    return "Test message";
  }
```

* Provide your asynchronous value within the Completed class; if you don't provide this value, a default message will be displayed.
```
  completed: Completed(
    completedMsgFuture: getDelayedMessage()
  ),
```
What do you think about this solution ?

**Comment by alexaungmyooo** [comment]
believe Solution 2 is the better choice as it keeps the API cleaner and separates the concerns effectively. Using completedMsgFuture allows for asynchronous message updates without adding extra complexity to pd.update(). It’s more modular and better suited for cases where the final message depends on dynamic or async data.

**Comment by emreesen27** [comment]
Upgrade to version 1.2.0 to verify if this resolves your issue.

I also conducted a test based on your use case.
```dart
  Future<void> _fileMigrationExample(BuildContext context) async {
    final pd = ProgressDialog(context: context);
    final completer = Completer<String>();

    // Generate dummy file list
    final files = List.generate(20, (index) => "file_${index + 1}.txt");
    final totalFiles = files.length;

    pd.show(
      max: totalFiles,
      msg: "Files migrating...",
      msgMaxLines: 4,
      completed: Completed(
        completedMsg: "Processing files...", // Initial message
        completedMsgFuture: completer.future,
        completionDelay: 2000,
      ),
    );

    int successCount = 0;
    int errorCount = 0;

    // Simulate file processing
    for (var file in files) {
      try {
        // Simulate processing time
        await Future.delayed(Duration(milliseconds: 200));

        // Simulate random error (10% chance)
        if (Random().nextDouble() < 0.1) {
          throw Exception('Failed to process $file');
        }

        successCount++;
        pd.update(
          value: successCount + errorCount,
          msg: "Processing $file...", // Current file
        );
      } catch (e) {
        errorCount++;
        pd.update(
          value: successCount + errorCount,
          msg: "Error in $file...", // Error state
        );
      }
    }

    // Complete with final summary message
    completer.complete("""Migration Summary:
   - Total Files: $totalFiles
   - Successful: $successCount
   - Failed: $errorCount""");
  }
```


https://github.com/user-attachments/assets/bcfc57e9-4aaf-48e5-906b-1ce2f7fd0657

**Comment by alexaungmyooo** [comment]
Thank you for the prompt response and for implementing this enhancement! I’ve tested the new feature in version 1.2.0, and it is working as expected. The ability to dynamically update the completed message fits perfectly with my use case.

The example provided was incredibly helpful and demonstrates the flexibility of the updated functionality. Using a Completer for the final summary works seamlessly and ensures the completed message accurately reflects the final state.

Thank you once again for addressing this request so efficiently! I truly appreciate your effort and support. 😊

**Comment by emreesen27** [comment]
I'm glad your problem was solved. It was a pleasure for me.
