### ISSUE TITLE
Progress bar value is incorrect if max is anything other than 100

### ISSUE THREAD

**Issue by meld-cp** [emreesen27/Flutter-Progress-Dialog#5]
Thanks for the handy package 👍 

Regarding this line:
https://github.com/emreesen27/Flutter-Progress-Dialog/blob/e5ea4b991f6c87cb000b35eb39fd1334206a3646/lib/progress_dialog.dart#L129

I think this should be:
```dart
value: (value / max) * 100, 
```
Otherwise there is a disconnect between the progress bar and value being updated.

You can see the problem if you set the max value to something big like 10000 and send updates from 1 to 10000.

**Comment by emreesen27** [comment]
Yes, you are right. I will take care of it as soon as possible.

**Comment by meld-cp** [comment]
Thank you. 😊  Should I do a pull request?

**Comment by emreesen27** [comment]
of course, as you wish

**Comment by emreesen27** [comment]
Thank you very much for your feedback. You can switch to version 1.0.0.

**Comment by meld-cp** [comment]
Thanks! :-)
