### ISSUE TITLE
when text length exeeds 10 charactor getting error pixel overflows.

### ISSUE THREAD

**Issue by prabuddaFernando** [emreesen27/Flutter-Progress-Dialog#7]
![image](https://user-images.githubusercontent.com/16753092/125567803-f553604f-d073-401b-b4d6-4127277f8dea.png)

```
 progressDialog?.show(
        max: 100,
        msg: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        barrierColor: Theme.of(context).backgroundColor);
```

**Comment by emreesen27** [comment]
Hi @prabuddaFernando ,
First of all sorry for the late reply. 

* Upgrade version to 1.0.3
* You can now set the variable "msgMaxLines".

 msgMaxLines: 1
 ![maslines1](https://user-images.githubusercontent.com/45034416/129473148-7fe91063-99b9-499a-9522-363d643b7610.png)

 msgMaxLines: 2
![maxlines2](https://user-images.githubusercontent.com/45034416/129473204-ea5cbf98-c6f7-460b-99ce-cc424a1f884a.png)
